server:
  name: EasyStoGu-Scheduled
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
spring:
  main:
    web-application-type: reactive
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: NON_NULL